### ISSUE TITLE
Exodus deadline: 1377993600

### ISSUE THREAD

**Issue by dexX7** [mastercoin-MSC/mastercoin-tools#24]
The Exodus deadline is actually 1377993600 (= Sun, 01 Sep 2013 00:00:00 GMT) and  not 1377993874.

The deadline is defined in msc_utils_parsing.py.

Tests:

``` python
# txid: 502a936801823437ce1f886ff3955618bbd7f88e9863ddd182045a625028e9ed
exodus_bootstrap_deadline = 1377993600
value = 10000000
block_timestamp = 1377844770
tx_sec_before_deadline = exodus_bootstrap_deadline - block_timestamp
bonus=max((tx_sec_before_deadline+0.0)/(3600*24*7*10.0)*100,0)
dacoins=str('{:.0f}'.format(int(value)*(100+bonus)))
print dacoins
# Result:
#1024608135 (correct)
```

``` python
# txid: 502a936801823437ce1f886ff3955618bbd7f88e9863ddd182045a625028e9ed
exodus_bootstrap_deadline = 1377993874
value = 10000000
block_timestamp = 1377844770
tx_sec_before_deadline = exodus_bootstrap_deadline - block_timestamp
bonus=max((tx_sec_before_deadline+0.0)/(3600*24*7*10.0)*100,0)
dacoins=str('{:.0f}'.format(int(value)*(100+bonus)))
print dacoins
# Result:
#1024653439 (sligthly off!)
```

Tx:
https://masterchain.info/simplesend.html?tx=502a936801823437ce1f886ff3955618bbd7f88e9863ddd182045a625028e9ed&currency=MSC
https://masterchest.info/lookuptx.aspx?txid=502a936801823437ce1f886ff3955618bbd7f88e9863ddd182045a625028e9ed

**Comment by dacoinminster** [comment]
Yeah, we had to move the deadline a bit for political reasons (people who
sent before the deadline but weren't recorded in the block-chain until
after the deadline). I believe all implementations are in consensus about
this.

**Comment by dexX7** [comment]
Yes, the explorers and wallets are fine, but the code wasn't updated and a mastercoin-tools build from scratch will yield slightly wrong numbers.

**Comment by dacoinminster** [comment]
Heh. I just noticed the "dacoins" variable in that code :-P

I support changing this code to match what we currently do in the wild.
(not sure how this could be different from what we do in the wild - anybody
know how that could have happened?)

**Comment by dexX7** [comment]
The "bug" was introduced here: https://github.com/grazcoin/mastercoin-tools/commit/9d0cf391d079b86dd8df8955250acf24c7175d82#diff-341c5fea68050221e3d2d1e80f679007 and was most likely related to block 255365. This block was mentioned in the spec and has the timestamp (1377993874, 01 Sep 2013 00:04:34) which was used in the code.

**Comment by grazcoin** [comment]
I have found this bug few days ago (April 3rd) as well, and I have a fix, but I am travelling at the moment. I could push it in few days.

The fix is:
msc_utils_parsing.py
exodus_bootstrap_orig_deadline=1377993600
exodus_bootstrap_deadline=1377993874

on msc_bootstrap.py
change to tx_sec_before_deadline=exodus_bootstrap_orig_deadline-block_timestamp

**Comment by dexX7** [comment]
Sounds good @grazcoin. I verified both timestamps furthermore in https://github.com/mastercoin-MSC/spec/issues/126.

**Comment by ghost** [comment]
Thanks @grazcoin , updated our build with your fix.
