### ISSUE TITLE
Currency identifier confusion

### ISSUE THREAD

**Issue by achamely** [mastercoin-MSC/mastercoin-tools#25]
Currently the Mastercoin spec has currency id 0 as BTC, 1 as MSC and 2 as TMSC. 
The mastercoin-tools implementation (for file descriptions) seems to omit the BTC and use file name 0 for MSC and 1 for TMSC.  This can cause some confusion.  I would like to propose for consistency it match the spec currency id's. Setting this up before we start moving forward with Smart Properties will help reduce potential integration woes from new adopters.

**Comment by ripper234** [comment]
Sounds good.

**Comment by achamely** [comment]
Specifically my initial investigation looks like the update would be line 936 of msc_validate.py
The filename gets set by the dict index. If nothing else is dependent on this (besides the consensus checker scripts) then it should be just updating it to be +=1
