### ISSUE TITLE
Parse smart property names and properties from the blockchain

### ISSUE THREAD

**Issue by curtislacy** [mastercoin-MSC/mastercoin-tools#7]
Create a new data directory in its parsing/validation area for properties, and put a json file in for each currency ID. This is parsing/validation of transaction 50.
Also add the balance to the issuing address.

**Comment by ghost** [comment]
Will the data directory store all transactions that are SP related? ie. /properties/properties-38809ed... ?

**Comment by curtislacy** [comment]
The transactions themselves should still be in /tx.  But all the other detail about properties (https://github.com/faizkhan00/mastercoin-tools/blob/msc_smartproperty/scripts/smartproperty_issuance_example.json#L6-L10) should be in files in /properties.  So like /properties/34.json would have details about SP ID 34.

**Comment by ghost** [comment]
inital validation added in 60293f6

Should add properties json for every property

balances not yet added

**Comment by curtislacy** [comment]
Nice!  Balances will happen under this one: https://github.com/mastercoin-MSC/mastercoin-tools/issues/8
