### ISSUE TITLE
Process simple send of smart properties

### ISSUE THREAD

**Issue by curtislacy** [mastercoin-MSC/mastercoin-tools#8]
Pretty much requires mastercoin-MSC/omniwallet#294

Support fixed-number sends.
Calculate balances.

**Comment by curtislacy** [comment]
https://github.com/mastercoin-MSC/mastercoin-tools/blob/master/msc_validate.py#L57-L60 needs to not be a hard-coded set of lookups.  We can load in the data produced by https://github.com/mastercoin-MSC/mastercoin-tools/issues/7 at the beginning of msc_validate and make build this lookup based on what we've parsed previously.

**Comment by curtislacy** [comment]
One note on the above - to avoid name conflicts, we have to make sure that the names parsed in #7 include the property ID (I believe this is a behavior defined in the spec as well).  That way no one can create a new property with an existing name and squash someone else's submission.

**Comment by curtislacy** [comment]
[4/1/14 4:16:29 PM] Curtis Lacy: Okay, so let's assume the flow so far is this:
[4/1/14 4:16:46 PM] Curtis Lacy: 1. When we parse, we put all the issuance transactions into tx
[4/1/14 4:17:31 PM] Curtis Lacy: 2. We also put all the sends and things having to do with SPs in there with a currency_id_str of "Smart Property", because we need something to put in there and we don't have a name yet.
[4/1/14 4:17:39 PM] Curtis Lacy: 3. Validation starts.
[4/1/14 4:18:18 PM] Curtis Lacy: 4. We go through and validate just the property creations, and fill out both /properties/ and coins_dict.
[4/1/14 4:18:46 PM] Curtis Lacy: 5. We validate all the balance and send transactions, only now we have names to put in currency_id_str.

**Comment by dacoinminster** [comment]
Hmmm. This sounds like making two passes through all transactions, which
shouldn't be necessary. Won't there be a table of properties indexed by ID
number which gets updated as we make our first (and only) pass through the
transactions? Won't all transactions which reference created properties
necessarily be later in the chain of transactions, when we already know the
name?

Perhaps I am misunderstanding what is being discussed here?

**Comment by ghost** [comment]
Well, I think this is on more of a micro level back-and-forth between the parser and the validation engine (checks transactions for validity).

There will be a folder of properties referenced by ID that will be used to lookup information on a given property. Your second point is also valid, but considering the first time through, we need a generic way to tag these property creation transactions and then run them through the validator to be stored in the folder of properties for later use.

It should be addressed by #16

**Comment by dacoinminster** [comment]
By "folder" do you mean "SQL table"? Or is that a future optimization we
need to make?

**Comment by ghost** [comment]
By "folder" do you mean "SQL table"? 

Absolutely not, all data produced by the mastercoin-tools repository is stored discreetly and directly into flat files on the host system

...

Yes, we realize this is kind of an odd design choice, for security and flexibility, but right now there's no real movement to change it.

**Comment by dacoinminster** [comment]
OK - Hopefully we'll notice any scalability issues with flat files before
they bite us :)

Is it safe to assume that the flat files are written sequentially (no
inefficient inserts mid-file) and that smart property data is stored in an
array in RAM for most uses (i.e. not parsing the file over and over and
over again)?

**Comment by ghost** [comment]
Our flat files are written sequentially, yes. Most of the work involved in maintaining file objects is handled by Python automatically but we make sure to close file objects immediately as we're done with them to prevent overwrites, thrashing, that sort of thing.

Smart property data is loaded into Python's internal dictionary datatype and then accessed from process memory, we don't want to or try to reload the file from disk more than once.

**Comment by ghost** [comment]
intial pr in

**Comment by ripper234** [comment]
Issue #249 is targeted for the next milestone - that should have the design of moving away from flat flies into a proper data store layer.
